### ISSUE TITLE
API with other url

### ISSUE THREAD

**Issue by LyonelB** [Nomy/tunein-air-api-php#1]
Hello,

Congratulations on your API!
I use Icecast 2.3 so I can not use your API.
But my broadcast software generates a URL containing the title and artist being broadcast: http://www.urban-radio.com/titrage/title_winmedia.html

Can I use this URL with your API?

Best regards

**Comment by Nomy** [comment]
It should be posible. I'll get back with different version where it gets title in plain text from a url.

**Comment by LyonelB** [comment]
Great !
Thanks a lot

**Comment by Nomy** [comment]
Try this: https://github.com/Nomy/tunein-air-api-php-url
It's untested.

**Comment by LyonelB** [comment]
Great !
Thanks a lot

2016-10-24 14:53 GMT+02:00 Nomy notifications@github.com:
